
login()::=<<
<h3>Login With Account</h3>
<form method="POST" action="">
Email:<br>
<input type="text" name="email" size="100" value="test@example.org"><br>
Password:<br>
<input type="password" name="password" size="100" value="testtest"><br>
<input type="submit" name="authenticate" value="Login"><br>
</form>
<h3>Create New Account</h3>
<form method="POST" action="">
Email:<br>
<input type="text" name="email" size="100" value="test@example.org"><br>
Password:<br>
<input type="password" name="password" size="100" value="testtest"><br>
<input type="submit" name="register" value="Create Account"><br>
</form>
>>