# This workflow runs the deployJavadoc gradle task and then deploys the javadoc files to GitHub pages.
# The javadoc files are stored inside the "latest" directory.

name: Deploy Javadoc (latest)

# Triggers the workflow on push to master
on: 
  push:
    branches:
      - master

jobs:
  deploy-javadoc-latest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Set up node
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew deployJavadoc
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.0.0
      with:
        branch: gh-pages # deploy javadoc on gh-pages branch
        folder: javadoc # folder that should be deployed
        target-folder: latest # where to store the javadoc files