name: Publish artifacts as snapshot to github packages

# Run workflow on publish to develop branch automatically.
# Also allow to run the workflow manually on every other branch.
on:
  push:  
    branches:
      - fix/agentNotFound
  workflow_dispatch:


jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Set up node
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle and publish as snapshot to archiva
      env:
        USERNAME: ${{ secrets.USERNAME }}
        Token: ${{ secrets.TOKEN }}
      run: ./gradlew publish
    - name: Upload artifacts on GitHub (attached to this workflow)
      uses: actions/upload-artifact@v2
      with:
        name: las2peer
        path: |
          core/export/jars/las2peer-*.jar
          restmapper/export/jars/las2peer-rest-mapper*.jar
          webconnector/export/jars/las2peer-web-connector*.jar
          bundle/export/jars/las2peer-bundle-*.jar
